### ISSUE TITLE
[BUG] The howitzer does not work

### ISSUE THREAD

**Issue by Stone3006** [Pabilo8/ImmersiveIntelligence#111]
Its not only the howitzer there are also other bugs like the machine gun and the hammer when being charged
the howitzer does no form even if I reset and re download it I also used the projector to instantly build it but it still does not work no matter what I do.
the hammer makes the charging station rotate every time I use it and then disappear when I take it.
the machine gun does not shoot can be reloaded but cannot shoot the 4th time I tried it it stopped to reload now its just a prop.

I really hope that the dev will fix this

**Comment by reimse** [comment]
Dear Stone3006,
I know your problem and found (maybe) the issue and the solution! I hope you haven't gave up the mod, because he is very cool! The issue is maybe made by Immersive Petroleum and not Immersive Intelligence! The projector shows the model mirrored, but not every structure is available to mirrior.
If you use the Projektor, Press shift und the scrooling thing on your mouse, to mirror it. after it it should work!
Sorry for my bad English. (if you speak german i can help more)
If you need more help just write to me!

**Comment by Stone3006** [comment]
I am(still) learning a bit of german( I only know 5 words for now). But I
did it all im still suing the mod cuz the sandbags are amazing I built it
using the quick build in immersive petroleum(projector) also built it
manually I reseted the whole game and mod also my minecraft because it was
the only artillery mod that works like one.

**Comment by reimse** [comment]
Does it have worked?

**Comment by Stone3006** [comment]
nai

**Comment by reimse** [comment]
The Projector Shows it mirrored (to mirror the projection you Need to press Shift and Press in the wheel in the Mouse! Not rotate the wheel, Press it!). So you have in every Site an Input.... On the Front ist the Concrete Block with Ammo Input and Output. On the Back ist the Redstone Port, for Open the "Gate" (i have not find any Others Word). On the Rigth ist the Data Port, where you can Connect it to the "Network". On the left is the Energy Port (from any other Mod or HV). And If you have build it Like I sayed it should Work. If you want a Pictures, you can watch this Video https://youtu.be/o3mt9exEfL0 (i mean the constructing)

**Comment by Stone3006** [comment]
Sorry Like I said i did all that I really like this mod im just looking for
a way to solve this bug I built it on survival and creative projector no
projector i pressed all block none.worked.
